---
- hosts: ec2-instance

  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce and docker-compose
      apt:
        pkg:
          - docker-ce
          - docker-compose
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: "Creating folder and copying html file"
      file:
        path: "/myfile"
        state: directory
    - name: "Copying local files"
      copy:
        src: "index.html"
        dest: "/myfile/"
    - name: Creating container using HTTPD Image
      docker_container:
        name: "MyWebServer3"
        image: "httpd"
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
        volumes:
        - /myfile:/usr/local/apache2/htdocs/
    - name: Get instance profile info
      amazon.aws.aws_caller_info:
      register: aws_info

    - set_fact:
        ecr_registry_url: "998171272878.dkr.ecr.us-east-1.amazonaws.com/docker-repository-comit-2023"

    - name: Get ECR token
      shell: "aws ecr get-login-password --region eu-east-1"
      register: ecr_token

    - name: Log into ECR registry
      docker_login:
        registry_url: "998171272878.dkr.ecr.us-east-1.amazonaws.com/docker-repository-comit-2023"
        debug: yes
        username: "AWS"
        password: "{{ ecr_token.stdout }}"
        reauthorize: yes
    #- name: pull an image
    #  docker_image:
    #    name: 998171272878.dkr.ecr.us-east-1.amazonaws.com/docker-repository-comit-2023:latest
    #    source: pull
