---
- hosts: ec2-instance

  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce and docker-compose
      apt:
        pkg:
          - docker-ce
          - docker-compose
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Download the awscli bundle.
      get_url: url=https://s3.amazonaws.com/aws-cli/awscli-bundle.zip dest=/tmp/awscli-bundle.zip
      register: aws_cli_download_bundle

    - name: Unarchive the installer.
      unarchive: src=/tmp/awscli-bundle.zip dest=/tmp copy=no creates=/tmp/awscli-bundle
      when: aws_cli_download_bundle.changed
      register: aws_cli_unarchive_installer

    - name: Install awscli package.
      shell: python /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/bin/aws
      args:
        creates: /usr/bin/aws
      when: aws_cli_unarchive_installer.changed

    - name: Configure AWS.
      shell: aws configure set {{item.key}} {{item.value}} --profile {{aws_profile}}
      no_log: False
      with_dict:
        aws_access_key_id: "{{aws_access_key}}"
        aws_secret_access_key: "{{aws_secret_key}}"
        region: "{{aws_region}}"
        format: "{{aws_format}}"
      become_user: "{{aws_system_user}}"
      changed_when: false
    #- name: pull an image
    #  docker_image:
    #    name: 998171272878.dkr.ecr.us-east-1.amazonaws.com/docker-repository-comit-2023:latest
    #    source: pull
